### ISSUE TITLE
The demo is not working

### ISSUE THREAD

**Issue by InnocentRoot** [Grafikart/CustomElement-SpinningDots#1]
The demo page at [https://grafikart.github.io/CustomElement-SpinningDots/](url) isn't showing the spinner.

**My Browser:** Edge ( chromium based)
**CustomElement-SpinningDots Release version:** 1.0.0

**Comment by hanako-eo** [comment]
it's normal our dear grafikart to forget this line 
```js
customElements.define('spinning-dots', SpinningDots)
```

**Comment by hanako-eo** [comment]
resolve !! @InnocentRoot

**Comment by InnocentRoot** [comment]
Thanks
